//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TPARCHIPERCEPTRON.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Dessin
    {
        public int ID { get; set; }
        public int Taille { get; set; }
        public string Coordonnées { get; set; }
        public string Charactère { get; set; }
    }
}
